theme: minima
title: Your rockin crib
author: swagl0rd
email: your-email@domain.com
description: > whatever this man said

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
